name: Publish Docker Images
on:
  push:
    tags:
      - '*'

jobs:
  push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'checkout the source code'
        uses: actions/checkout@main

      - name: 'login to container registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'build inventory image'
        run: |
          docker build . --tag ghcr.io/ngn13/ctorm:latest ghcr.io/ngn13/ctorm:${GITHUB_REF##*/}
          docker push ghcr.io/ngn13/ctorm:${GITHUB_REF##*/}
          docker push ghcr.io/ngn13/ctorm:latest
