name: Docker

on:
  push:
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  IMAGE: ${{github.repository}}

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: 'checkout the source code'
        uses: actions/checkout@main

      - name: 'login to container registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'build inventory image'
        run: |
          docker build . \
            --tag ${{env.REGISTRY}}/${{env.IMAGE}}:latest \
            --tag ${{env.REGISTRY}}/${{env.IMAGE}}:${GITHUB_REF##*/}
          docker push ${{env.REGISTRY}}/${{env.IMAGE}}:latest
          docker push ${{env.REGISTRY}}/${{env.IMAGE}}:${GITHUB_REF##*/}
