name: Docker

on:
  push:
    tags:
      - "*"

env:
  REGISTRY: ghcr.io
  IMAGE: ${{github.repository}}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to container repo
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/i386
          tags: |
            ${{env.REGISTRY}}/${{env.IMAGE}}:latest
            ${{env.REGISTRY}}/${{env.IMAGE}}:${GITHUB_REF##*/}
