name: Run Test Scripts
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout the source code'
        uses: actions/checkout@v3

      - name: 'install dependencies'
        run: |
          sudo apt-get update
          sudo apt-get install -y jq gcc make libcjson-dev

      - name: 'build the library'
        run: make

      - name: 'build the examples'
        run: make example

      - name: 'run example #1'
        run: ./scripts/test.sh 1

      - name: 'run example #2'
        run: ./scripts/test.sh 2

      - name: 'run example #3'
        run: ./scripts/test.sh 3

      - name: 'run example #4'
        run: ./scripts/test.sh 4
