name: Tests

on:
  push:
    paths-ignore:
      - ".github/workflows/docker.yml"
      - "docs/*"
      - ".clang-format"
      - "Dockerfile"
      - "Doxyfile"
      - "README.md"
      - "LICENSE.txt"
    branches:
      - "main"

  pull_request:
    paths-ignore:
      - ".github/workflows/docker.yml"
      - "docs/*"
      - ".clang-format"
      - "Dockerfile"
      - "Doxyfile"
      - "README.md"
      - "LICENSE.txt"
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the source code"
        uses: actions/checkout@v3

      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y make clang-format-19 black

      - name: "Check formatting"
        run: make check

  test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the source code"
        uses: actions/checkout@v3

      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y jq gcc make libcjson-dev

      - name: "Build the library"
        run: make

      - name: "Build the examples"
        run: make example

      - name: "Run example #1"
        run: ./scripts/test.sh 1

      - name: "Run example #2"
        run: ./scripts/test.sh 2

      - name: "Run example #3"
        run: ./scripts/test.sh 3

      - name: "Run example #4"
        run: ./scripts/test.sh 4

      - name: "Run example #5"
        run: ./scripts/test.sh 5
